# ============================================================================
# Grafana main configuration file
# Official docs: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
# ============================================================================

# [server] Server configuration
# Used to configure basic settings for the Grafana HTTP server
[server]
# Protocol type
protocol = http

# HTTP service listening port
http_port = 3000

# [security] Security configuration
# Used to configure security-related default settings for Grafana
[security]
# Default Grafana admin username
admin_user = admin

# Default Grafana admin password
admin_password = 123456

# If you are hosting Grafana behind HTTPS
;cookie_secure = true

# Instructs the browser to allow rendering Grafana in <frame>, <iframe>, <embed>, or <object> elements
;allow_embedding = true

# [users] User configuration
# Used to configure user-related default settings
[users]
# Placeholder text for the login/username input on the login page
;login_hint = test

# Placeholder text for the password input on the login page
;password_hint = 123456

# Default UI theme
default_theme = system

# Default interface language
default_language = zh-Hans

# [dashboards] Dashboard configuration
# Used to configure dashboard-related default settings
[dashboards]
# Default home dashboard path
default_home_dashboard_path = /etc/grafana/dashboards/fba_server.json
