insert into sys_dict_type (id, name, code, remark, created_time, updated_time)
values
(1, 'Estado general', 'sys_status', 'Estado general del sistema: 1/0', now(), null),
(2, 'Interruptor general', 'sys_choose', 'Interruptor general del sistema: true/false', now(), null),
(3, 'Tipo de menú', 'sys_menu_type', 'Tipo de menú del sistema', now(), null),
(4, 'Estado de acceso', 'sys_login_status', 'Estado de acceso del usuario', now(), null),
(5, 'Operador de regla de datos', 'sys_data_rule_operator', 'Operador de la regla de permisos de datos', now(), null),
(6, 'Expresión de regla de datos', 'sys_data_rule_expression', 'Expresión de la regla de permisos de datos', now(), null),
(7, 'Parámetros del frontend', 'sys_frontend_config', 'Tipo de configuración de parámetros del frontend', now(), null),
(8, 'Tipo de estrategia de tarea', 'task_strategy_type', 'Tipo de estrategia de tarea programada', now(), null),
(9, 'Tipo de periodo de tarea', 'task_period_type', 'Tipo de periodo de tarea programada', now(), null),
(10, 'Notificaciones y anuncios', 'notice', 'Tipo de notificación', now(), null),
(11, 'Estado en línea', 'user_online_status', 'Estado en línea del usuario', now(), null),
(12, 'Tipo de plugin', 'sys_plugin_type', 'Tipo de plugin', now(), null);

insert into sys_dict_data (id, type_code, label, value, color, sort, status, remark, type_id, created_time, updated_time)
values
(1, 'sys_status', 'Deshabilitado', '0', 'red', 1, 1, 'Estado deshabilitado', 1, now(), null),
(2, 'sys_status', 'Normal', '1', 'green', 2, 1, 'Estado normal', 1, now(), null),
(3, 'sys_choose', 'Desactivado', 'false', 'error', 1, 1, 'Estado desactivado', 2, now(), null),
(4, 'sys_choose', 'Activado', 'true', 'success', 2, 1, 'Estado activado', 2, now(), null),
(5, 'sys_menu_type', 'Directorio', '0', 'orange', 1, 1, 'Directorio de menú', 3, now(), null),
(6, 'sys_menu_type', 'Menú', '1', 'default', 2, 1, 'Menú normal', 3, now(), null),
(7, 'sys_menu_type', 'Botón', '2', 'processing', 3, 1, 'Botón de menú', 3, now(), null),
(8, 'sys_menu_type', 'Incrustado', '3', 'cyan', 4, 1, 'Página incrustada', 3, now(), null),
(9, 'sys_menu_type', 'Enlace', '4', 'purple', 5, 1, 'Enlace externo', 3, now(), null),
(10, 'sys_login_status', 'Fallido', '0', 'error', 1, 1, 'Estado de acceso fallido', 4, now(), null),
(11, 'sys_login_status', 'Éxito', '1', 'success', 2, 1, 'Estado de acceso exitoso', 4, now(), null),
(12, 'sys_data_rule_operator', 'AND', '0', 'green', 1, 1, 'Operador lógico AND', 5, now(), null),
(13, 'sys_data_rule_operator', 'OR', '1', 'gold', 2, 1, 'Operador lógico OR', 5, now(), null),
(14, 'sys_data_rule_expression', 'Igual a (==)', '0', 'success', 1, 1, 'Expresión de comparación igual a', 6, now(), null),
(15, 'sys_data_rule_expression', 'Distinto de (!=)', '1', 'error', 2, 1, 'Expresión de comparación distinto de', 6, now(), null),
(16, 'sys_data_rule_expression', 'Mayor que (>)', '2', 'magenta', 3, 1, 'Expresión de comparación mayor que', 6, now(), null),
(17, 'sys_data_rule_expression', 'Mayor o igual que (>=)', '3', 'volcano', 4, 1, 'Expresión de comparación mayor o igual que', 6, now(), null),
(18, 'sys_data_rule_expression', 'Menor que (<)', '4', 'gold', 5, 1, 'Expresión de comparación menor que', 6, now(), null),
(19, 'sys_data_rule_expression', 'Menor o igual que (<=)', '5', 'orange', 6, 1, 'Expresión de comparación menor o igual que', 6, now(), null),
(20, 'sys_data_rule_expression', 'Incluye (in)', '6', 'purple', 7, 1, 'Expresión de inclusión', 6, now(), null),
(21, 'sys_data_rule_expression', 'No incluye (not in)', '7', 'error', 8, 1, 'Expresión de exclusión', 6, now(), null),
(22, 'sys_frontend_config', 'No', '0', 'red', 1, 1, 'No es una configuración de parámetros del frontend', 7, now(), null),
(23, 'sys_frontend_config', 'Sí', '1', 'green', 2, 1, 'Es una configuración de parámetros del frontend', 7, now(), null),
(24, 'task_strategy_type', 'Interval (intervalo)', '0', 'cyan', 1, 1, 'Estrategia de intervalo de tiempo', 8, now(), null),
(25, 'task_strategy_type', 'Crontab (programado)', '1', 'purple', 2, 1, 'Estrategia de expresión horaria', 8, now(), null),
(26, 'task_period_type', 'Días', 'days', 'processing', 1, 1, 'Tipo de periodo de tarea programada - días', 9, now(), null),
(27, 'task_period_type', 'Horas', 'hours', 'magenta', 2, 1, 'Tipo de periodo de tarea programada - horas', 9, now(), null),
(28, 'task_period_type', 'Minutos', 'minutes', 'volcano', 3, 1, 'Tipo de periodo de tarea programada - minutos', 9, now(), null),
(29, 'task_period_type', 'Segundos', 'seconds', 'gold', 4, 1, 'Tipo de periodo de tarea programada - segundos', 9, now(), null),
(30, 'task_period_type', 'Microsegundos', 'microseconds', 'warning', 5, 1, 'Tipo de periodo de tarea programada - microsegundos', 9, now(), null),
(31, 'notice', 'Notificación', '0', 'magenta', 1, 1, 'Tipo de notificación', 10, now(), null),
(32, 'notice', 'Anuncio', '1', 'purple', 2, 1, 'Tipo de anuncio', 10, now(), null),
(33, 'user_online_status', 'Desconectado', '0', 'warning', 1, 1, 'Estado desconectado del usuario', 11, now(), null),
(34, 'user_online_status', 'En línea', '1', 'success', 2, 1, 'Estado en línea del usuario', 11, now(), null),
(35, 'sys_plugin_type', 'Archivo comprimido', '0', 'gold', 1, 1, 'Tipo de plugin - archivo comprimido', 12, now(), null),
(36, 'sys_plugin_type', 'GIT', '1', 'processing', 2, 1, 'Tipo de plugin - GIT', 12, now(), null);

select setval(pg_get_serial_sequence('sys_dict_type', 'id'),coalesce(max(id), 0) + 1, true) from sys_dict_type;
select setval(pg_get_serial_sequence('sys_dict_data', 'id'),coalesce(max(id), 0) + 1, true) from sys_dict_data;
